server:
  port: 9091


spring:
  application:
    name: SKILL-SERVICE
  config:
        activate:
            on-profile: dev
  data:
    mongodb:
      uri: mongodb+srv://root:WBJsDZphl9loQGt4@mongodb.lqmn4.mongodb.net/onboarding-prudential?retryWrites=true&w=majority

#  zipkin:
#    base-url: http://127.0.0.1:9411/
    
logging:
  file.name: C:/Users/002TCO744/Desktop/elk-logs/skill-service.log

#department:
#  service:
#    url: http://DEPARTMENT-SERVICE

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
   
  