server:
  port: 9091


spring:
  application:
    name: SKILL-SERVICE
  config:
        activate:
            on-profile: dev
  data:
    mongodb:
      host: 10.5.0.7
      port: 27017
      database: mydb

#  zipkin:
#    base-url: http://127.0.0.1:9411/
    
logging:
  file.name: C:/Users/002TCO744/Desktop/elk-logs/skill-service.log
  
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:10.5.0.5}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://10.5.0.5:8761/eureka

#department:
#  service:
#    url: http://DEPARTMENT-SERVICE

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
   
  